/* Regency Events AV Tracker V51 feature layer */
(function(){
'use strict';
const V51_KEY='regency_v51_features';
function uid(p){return (typeof makeId==='function'?makeId(p):p+'_'+Date.now()+'_'+Math.random().toString(36).slice(2));}
function escV(s){return typeof esc==='function'?esc(String(s??'')):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function ensureV51(){
 data.v51=data.v51||{};
 data.v51.documents=Array.isArray(data.v51.documents)?data.v51.documents:[];
 data.v51.hireVehicles=Array.isArray(data.v51.hireVehicles)?data.v51.hireVehicles:[];
 data.v51.vehicleFiles=Array.isArray(data.v51.vehicleFiles)?data.v51.vehicleFiles:[];
 return data.v51;
}
function persist(){try{if(typeof save==='function')save();else localStorage.setItem('avtracker_v1',JSON.stringify(data));}catch(e){console.error('V51 save',e)}}
function me(){return typeof currentUser==='function'?currentUser():null}
function fileSize(n){if(!n)return '';const u=['B','KB','MB','GB'];let i=0,x=n;while(x>=1024&&i<3){x/=1024;i++}return x.toFixed(i?1:0)+' '+u[i]}
async function uploadV51File(file,folder,ownerId){
 if(!file)return null;
 const rec={id:uid('file'),name:file.name,type:file.type||'application/octet-stream',size:file.size,createdAt:new Date().toISOString(),ownerId:ownerId||me()?.id||null,folder};
 if(typeof cloudIsReady==='function'&&cloudIsReady()&&typeof supabaseClient!=='undefined'){
   const org=(typeof REGENCY_ORG_ID!=='undefined'?REGENCY_ORG_ID:'regency');
   const path=org+'/v51/'+folder+'/'+rec.id+'_'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_');
   const {error}=await supabaseClient.storage.from('regency-hs').upload(path,file,{upsert:true,contentType:rec.type});
   if(error){console.error(error);alert('The file could not be uploaded to the cloud.');return null}
   rec.cloudPath=path; rec.cloudOnly=true;
 }else{
   if(file.size>2*1024*1024){alert('This file is over 2 MB. Connect to Cloud Login before uploading larger files.');return null}
   rec.localData=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});
 }
 return rec;
}
async function fileLink(rec){
 if(!rec)return null;
 if(rec.localData)return rec.localData;
 if(rec.cloudPath&&typeof cloudIsReady==='function'&&cloudIsReady()&&typeof supabaseClient!=='undefined'){
   const {data:d,error}=await supabaseClient.storage.from('regency-hs').createSignedUrl(rec.cloudPath,3600);if(!error)return d?.signedUrl||null;
 }
 return null;
}
async function deleteV51File(rec){
 if(rec?.cloudPath&&typeof cloudIsReady==='function'&&cloudIsReady()&&typeof supabaseClient!=='undefined')try{await supabaseClient.storage.from('regency-hs').remove([rec.cloudPath])}catch(e){}
}

/* ---------- My Documents ---------- */
const docTypes=[['certificate','📜','Certificates'],['right_to_work','🪪','Right to work'],['driving_licence','🚗','Driving licence'],['qualification','🎓','Qualifications'],['other','📁','Other documents']];
window.openMyDocuments=async function(){
 const u=me();if(!u)return typeof showLoginOverlay==='function'?showLoginOverlay():null;
 ensureV51();
 openModal('<div id="v51DocumentsModal"><div class="section-head"><div><h2 style="margin:0">📁 My Documents</h2><div class="muted">Your personal crew documents. Cloud files are private to the Regency app.</div></div><button class="secondary" onclick="closeModal();openCrewProfile()">← Profile</button></div><div id="v51DocList">Loading…</div></div>');
 await renderMyDocuments();
}
window.renderMyDocuments=async function(){
 const el=document.getElementById('v51DocList');if(!el)return;const u=me();const docs=ensureV51().documents.filter(x=>x.userId===u?.id);
 el.innerHTML=docTypes.map(([type,icon,label])=>{const arr=docs.filter(x=>x.type===type);return `<div class="v51-doc-group"><div class="v51-doc-head"><b>${icon} ${label}</b><label class="v51-upload">＋ Add<input type="file" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx" onchange="addMyDocument('${type}',this.files[0]);this.value=''" hidden></label></div>${arr.length?arr.map(x=>`<div class="v51-file-row"><div><b>${escV(x.name)}</b><div class="small muted">${escV(fileSize(x.size))} • ${new Date(x.createdAt).toLocaleDateString('en-GB')}</div></div><div class="v51-file-actions"><button class="secondary" onclick="viewV51File('${x.id}')">View</button><button class="danger" onclick="deleteMyDocument('${x.id}')">Delete</button></div></div>`).join(''):'<div class="small muted">No document uploaded</div>'}</div>`}).join('');
}
window.addMyDocument=async function(type,file){
 const u=me();if(!u||!file)return;const rec=await uploadV51File(file,'crew-documents',u.id);if(!rec)return;rec.userId=u.id;rec.type=type;ensureV51().documents.push(rec);persist();await renderMyDocuments();
}
window.deleteMyDocument=async function(id){const v=ensureV51();const i=v.documents.findIndex(x=>x.id===id);if(i<0)return;if(!confirm('Delete this document?'))return;const rec=v.documents[i];await deleteV51File(rec);v.documents.splice(i,1);persist();renderMyDocuments()}
window.viewV51File=async function(id){const rec=ensureV51().documents.find(x=>x.id===id)||ensureV51().vehicleFiles.find(x=>x.id===id);const url=await fileLink(rec);if(!url)return alert('This file is not available on this device.');window.open(url,'_blank','noopener')}

/* ---------- Hire Vehicles ---------- */
function vehicleStatus(v){const now=new Date();const from=v.start?new Date(v.start+'T00:00:00'):null;const to=v.end?new Date(v.end+'T23:59:59'):null;if(v.returned)return 'Returned';if(from&&now<from)return 'Booked';if(to&&now>to)return 'Overdue';return 'On hire'}
function vehicleStatusClass(s){return s.toLowerCase().replace(/\s+/g,'-')}
window.openHireVehicles=function(){showPage('hireVehicles');renderHireVehicles()}
window._v51SetFilter=function(x){window._v51VehicleFilter=x;renderHireVehicles()}
window._v51SetSearch=function(x){window._v51VehicleSearch=x;renderHireVehicles()}
window.renderHireVehicles=function(){
 const el=document.getElementById('hireVehicles');if(!el)return;const v=ensureV51().hireVehicles.slice().sort((a,b)=>(a.start||'').localeCompare(b.start||''));
 el.innerHTML=`<div class="card"><div class="section-head"><div><h2 style="margin:0">🚐 Hire Vehicles</h2><div class="muted">Track hired vans, cars and specialist vehicles, documents and return condition.</div></div><button onclick="newHireVehicle()">＋ Hire vehicle</button></div><div class="v51-filter"><select id="v51VehicleFilter" onchange="_v51SetFilter(this.value)"><option value="">All vehicles</option><option>Booked</option><option>On hire</option><option>Overdue</option><option>Returned</option></select><input id="v51VehicleSearch" placeholder="Search vehicle, supplier or customer" oninput="_v51SetSearch(this.value)"></div><div id="v51VehicleList">${renderVehicleCards(v)}</div></div>`;
 const f=document.getElementById('v51VehicleFilter');if(f)f.value=window._v51VehicleFilter||'';
 const q=document.getElementById('v51VehicleSearch');if(q)q.value=window._v51VehicleSearch||'';
}
function renderVehicleCards(all){const f=window._v51VehicleFilter||'';const q=(window._v51VehicleSearch||'').toLowerCase();let arr=all.filter(v=>!f||vehicleStatus(v)===f).filter(v=>!q||[v.vehicle,v.registration,v.supplier,v.customer].join(' ').toLowerCase().includes(q));if(!arr.length)return '<div class="empty">No hire vehicles found.</div>';return arr.map(v=>{const st=vehicleStatus(v);return `<div class="v51-vehicle-card"><div class="v51-vehicle-title"><div><h3>${escV(v.vehicle||'Unnamed vehicle')}</h3><div class="asset-id">${escV(v.registration||'No registration')}</div></div><span class="v51-status ${vehicleStatusClass(st)}">${st}</span></div><div class="v51-grid"><div><small>Hire period</small><b>${escV(v.start||'Not set')} → ${escV(v.end||'Not set')}</b></div><div><small>Area</small><b>${escV(v.area||'Local')}</b></div><div><small>Supplier</small><b>${escV(v.supplier||'')}</b></div><div><small>Customer / job</small><b>${escV(v.customer||'')}</b></div></div><div class="small muted">${escV(v.contact||'')}${v.notes?' • '+escV(v.notes):''}</div><div class="v51-file-chips">${v.licenceFileId?'🪪 Licence':''}${v.agreementFileId?' 📄 Agreement':''}${(v.photoFileIds||[]).length?' 📷 '+v.photoFileIds.length+' photos':''}${v.conditionVideoId?' 🎥 Condition video':''}</div><div class="v51-actions"><button class="secondary" onclick="editHireVehicle('${v.id}')">Edit</button>${!v.returned?`<button onclick="returnHireVehicle('${v.id}')">Return vehicle</button>`:''}<button class="danger" onclick="deleteHireVehicle('${v.id}')">Delete</button></div></div>`}).join('')}
window.v51VehicleSearch=function(x){window._v51VehicleSearch=x;renderHireVehicles()}
window.newHireVehicle=function(){openHireVehicleForm(null)}
window.editHireVehicle=function(id){openHireVehicleForm(ensureV51().hireVehicles.find(x=>x.id===id))}
function openHireVehicleForm(v){v=v||{id:uid('hire'),area:'Local',photoFileIds:[]};window._v51EditingVehicle=v.id;openModal(`<div><div class="section-head"><div><h2 style="margin:0">🚐 ${v.registration?'Edit':'Hire'} vehicle</h2></div><button class="secondary" onclick="closeModal();openHireVehicles()">Cancel</button></div><div class="v51-form"><label>Vehicle / make & model<input id="hv_vehicle" value="${escV(v.vehicle||'')}"></label><label>Registration<input id="hv_reg" value="${escV(v.registration||'')}"></label><label>Supplier / hire company<input id="hv_supplier" value="${escV(v.supplier||'')}"></label><label>Supplier contact<input id="hv_contact" value="${escV(v.contact||'')}"></label><label>Hire start<input id="hv_start" type="date" value="${escV(v.start||'')}"></label><label>Hire end<input id="hv_end" type="date" value="${escV(v.end||'')}"></label><label>Area<select id="hv_area"><option>Local</option><option>UK</option><option>Europe</option></select></label><label>Customer / job<input id="hv_customer" value="${escV(v.customer||'')}"></label><label>Notes<textarea id="hv_notes">${escV(v.notes||'')}</textarea></label></div><h3>Documents & condition</h3><div class="v51-upload-grid"><label>Driving licence<input type="file" id="hv_licence" accept=".pdf,.jpg,.jpeg,.png"></label><label>Signed rental agreement<input type="file" id="hv_agreement" accept=".pdf,.jpg,.jpeg,.png"></label><label>Vehicle photo 1<input type="file" id="hv_photo1" accept="image/*"></label><label>Vehicle photo 2<input type="file" id="hv_photo2" accept="image/*"></label><label>Damage / condition video<input type="file" id="hv_video" accept="video/*"></label></div><button style="width:100%;margin-top:14px" onclick="saveHireVehicle('${v.id}',${!!v.registration})">Save vehicle</button></div>`);const a=document.getElementById('hv_area');if(a)a.value=v.area||'Local'}
window.saveHireVehicle=async function(id,existing){const v=ensureV51();let x=v.hireVehicles.find(z=>z.id===id);if(!x){x={id,photoFileIds:[]};v.hireVehicles.push(x)}x.vehicle=document.getElementById('hv_vehicle').value.trim();x.registration=document.getElementById('hv_reg').value.trim();x.supplier=document.getElementById('hv_supplier').value.trim();x.contact=document.getElementById('hv_contact').value.trim();x.start=document.getElementById('hv_start').value;x.end=document.getElementById('hv_end').value;x.area=document.getElementById('hv_area').value;x.customer=document.getElementById('hv_customer').value.trim();x.notes=document.getElementById('hv_notes').value.trim();if(!x.vehicle)return alert('Enter the vehicle name or registration.');const jobs=[['hv_licence','licenceFileId','hire-licence'],['hv_agreement','agreementFileId','hire-agreement'],['hv_video','conditionVideoId','hire-condition']];for(const [id2,key,folder] of jobs){const file=document.getElementById(id2)?.files?.[0];if(file){const rec=await uploadV51File(file,folder,x.id);if(rec){ensureV51().vehicleFiles.push(rec);x[key]=rec.id}}}for(const id2 of ['hv_photo1','hv_photo2']){const file=document.getElementById(id2)?.files?.[0];if(file){const rec=await uploadV51File(file,'hire-photos',x.id);if(rec){ensureV51().vehicleFiles.push(rec);x.photoFileIds=x.photoFileIds||[];if(x.photoFileIds.length<2)x.photoFileIds.push(rec.id)}}}x.updatedAt=new Date().toISOString();persist();closeModal();openHireVehicles()}
window.returnHireVehicle=function(id){const x=ensureV51().hireVehicles.find(v=>v.id===id);if(!x)return;openModal(`<h2>↩️ Return vehicle</h2><p>Record the vehicle's return condition before marking it available again.</p><label>Return notes<textarea id="hv_return_notes">${escV(x.returnNotes||'')}</textarea></label><label>Return condition video<input type="file" id="hv_return_video" accept="video/*"></label><label>Return photo<input type="file" id="hv_return_photo" accept="image/*"></label><button style="width:100%" onclick="completeVehicleReturn('${id}')">Mark returned</button>`) }
window.completeVehicleReturn=async function(id){const x=ensureV51().hireVehicles.find(v=>v.id===id);if(!x)return;x.returnNotes=document.getElementById('hv_return_notes').value;x.returned=true;x.returnedAt=new Date().toISOString();for(const [id2,key,folder] of [['hv_return_video','returnVideoId','hire-return'],['hv_return_photo','returnPhotoId','hire-return-photos']]){const f=document.getElementById(id2)?.files?.[0];if(f){const rec=await uploadV51File(f,folder,x.id);if(rec){ensureV51().vehicleFiles.push(rec);x[key]=rec.id}}}persist();closeModal();openHireVehicles()}
window.deleteHireVehicle=async function(id){if(!confirm('Delete this hire vehicle record?'))return;const v=ensureV51();const x=v.hireVehicles.find(z=>z.id===id);if(!x)return;const ids=[x.licenceFileId,x.agreementFileId,x.conditionVideoId,x.returnVideoId,x.returnPhotoId,...(x.photoFileIds||[])].filter(Boolean);for(const id2 of ids){const r=v.vehicleFiles.find(f=>f.id===id2);if(r)await deleteV51File(r)}v.hireVehicles=v.hireVehicles.filter(z=>z.id!==id);v.vehicleFiles=v.vehicleFiles.filter(f=>!ids.includes(f.id));persist();renderHireVehicles()}

/* ---------- Wage SSN ---------- */
window.openWageSetupV51=function(){const u=me();if(!u)return;const w=typeof ensureWageSettings==='function'?ensureWageSettings(u):(u.wageSettings||{});returnToProfileOnClose=true;openModal(`<h2>⚙️ Wage Setup</h2><p class="muted">Rates, tax and your National Insurance / Social Security number.</p><label>Standard Rate (£/hour)<input id="w_standard" type="number" min="0" step="0.01" value="${Number(w.standardRate||15).toFixed(2)}"></label><label>Enhanced Rate 1 (£/hour)<input id="w_enh1" type="number" min="0" step="0.01" value="${Number(w.enhanced1Rate||w.standardRate||15).toFixed(2)}"></label><label>Enhanced Rate 2 (£/hour)<input id="w_enh2" type="number" min="0" step="0.01" value="${Number(w.enhanced2Rate||w.standardRate||15).toFixed(2)}"></label><label>Tax deduction (%)<input id="w_tax" type="number" min="0" max="100" step="0.01" value="${Number(w.taxPercent||0).toFixed(2)}"></label><label>Social Security / National Insurance number<input id="w_ssn" autocomplete="off" value="${escV(w.socialSecurityNumber||'')}"></label><button style="width:100%;margin-top:10px" onclick="saveWageSetupV51()">Save Wage Setup</button>`)}
window.saveWageSetupV51=function(){const u=me();if(!u)return;u.wageSettings=u.wageSettings||{};const w=u.wageSettings;w.standardRate=Math.max(0,Number(document.getElementById('w_standard').value)||0);w.enhanced1Rate=Math.max(0,Number(document.getElementById('w_enh1').value)||0);w.enhanced2Rate=Math.max(0,Number(document.getElementById('w_enh2').value)||0);w.taxPercent=Math.max(0,Math.min(100,Number(document.getElementById('w_tax').value)||0));w.socialSecurityNumber=document.getElementById('w_ssn').value.trim();persist();returnToProfileOnClose=false;closeModal();openCrewProfile()}

/* ---------- UI hooks ---------- */
function addStyles(){if(document.getElementById('v51Styles'))return;const s=document.createElement('style');s.id='v51Styles';s.textContent=`
.v51-doc-group,.v51-vehicle-card{border:1px solid var(--regency-border);background:var(--regency-panel-2);border-radius:14px;padding:12px;margin:10px 0}.v51-doc-head,.v51-vehicle-title{display:flex;justify-content:space-between;align-items:center;gap:10px}.v51-upload{display:inline-block;padding:8px 11px;background:var(--regency-green);color:#fff;border-radius:9px;font-weight:800;cursor:pointer}.v51-file-row{display:flex;justify-content:space-between;align-items:center;gap:8px;padding:10px 0;border-top:1px solid var(--regency-border)}.v51-file-actions,.v51-actions{display:flex;gap:6px;flex-wrap:wrap}.v51-status{padding:5px 9px;border-radius:99px;font-size:11px;font-weight:800;background:#26362d;color:#9ff0bf}.v51-status.overdue{background:#451a1a;color:#ff9b9b}.v51-status.booked{background:#293248;color:#b9ccff}.v51-status.returned{background:#222;color:#bbb}.v51-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin:12px 0}.v51-grid>div{padding:8px;background:var(--regency-panel);border-radius:9px}.v51-grid small{display:block;color:var(--regency-muted)}.v51-grid b{display:block;margin-top:3px}.v51-filter{display:grid;grid-template-columns:150px 1fr;gap:8px;margin:12px 0}.v51-file-chips{font-size:12px;margin:9px 0;color:#6ee6a0}.v51-form{display:grid;grid-template-columns:1fr 1fr;gap:9px}.v51-form label,.v51-upload-grid label{display:block}.v51-form textarea{min-height:80px}.v51-upload-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.v51-upload-grid label{padding:10px;border:1px dashed var(--regency-border);border-radius:10px}.v51-upload-grid input{margin-top:6px}.v51-vehicle-card h3{margin:0 0 5px}.v51-actions{margin-top:12px}.danger{background:#7f2a2a!important;color:#fff!important}.v51-nav-hire{position:relative}.v51-nav-hire .nav-icon{font-size:18px}@media(max-width:520px){.v51-grid,.v51-form,.v51-upload-grid{grid-template-columns:1fr}.v51-filter{grid-template-columns:1fr}.v51-file-row{align-items:flex-start;flex-direction:column}.v51-file-actions{width:100%}}
`;document.head.appendChild(s)}
function addHireNav(){const nav=document.querySelector('.pwa-nav');if(!nav||document.getElementById('v51HireNav'))return;const btn=document.createElement('button');btn.id='v51HireNav';btn.className='v51-nav-hire';btn.innerHTML='<span class="nav-icon">🚐</span><span class="nav-label">Hire</span>';btn.onclick=openHireVehicles;const buttons=[...nav.querySelectorAll('button')];const portal=buttons.find(b=>b.innerText.includes('Portaloo'));if(portal)portal.after(btn);else nav.appendChild(btn)}
function addHireSection(){if(document.getElementById('hireVehicles'))return;const main=document.querySelector('main');if(!main)return;const sec=document.createElement('section');sec.id='hireVehicles';sec.className='hidden';main.appendChild(sec)}
function addHeaderQR(){const bar=document.querySelector('.header-statuses');if(!bar||document.getElementById('v51HeaderQR'))return;const b=document.createElement('button');b.id='v51HeaderQR';b.className='header-status';b.style.cssText='cursor:pointer;border:1px solid #25352b!important;background:#070a08!important;color:#fff!important';b.innerHTML='<span class="header-status-icon">⌕</span><div><small>QR</small><strong>Scan</strong></div>';b.onclick=()=>typeof startScan==='function'&&startScan();bar.appendChild(b)}
function addProfileButton(){const buttons=[...document.querySelectorAll('#modal button')];if(!buttons.length)return;const body=document.getElementById('modalBody');if(!body||!body.innerText.includes('Personal profile'))return;if(!document.getElementById('v51ProfileDocsBtn')){const b=document.createElement('button');b.id='v51ProfileDocsBtn';b.className='secondary';b.style.cssText='width:100%;margin:8px 0';b.innerHTML='📁 My Documents';b.onclick=openMyDocuments;body.appendChild(b)} }
function patchWage(){if(typeof openWageSetup==='function'&&!openWageSetup.__v51){const old=openWageSetup;function wrapped(){openWageSetupV51()}wrapped.__v51=true;window.openWageSetup=wrapped}}
function hook(){ensureV51();addStyles();addHireSection();addHireNav();addHeaderQR();patchWage();addProfileButton();}
const oldShowPage=window.showPage;if(oldShowPage&&!oldShowPage.__v51){window.showPage=function(p){if(p==='hireVehicles'){if(typeof requireLogin==='function'&&!requireLogin())return;['dashboard','create','equipment','events','jobs','portaloo','marquee','activity','notifications','hours','healthSafety','crewHealthSafety','crewLoginEdit','scanner','hireVehicles'].forEach(id=>{const el=document.getElementById(id);if(el)el.classList.toggle('hidden',id!==p)});if(typeof stopScan==='function')stopScan();renderHireVehicles();window.scrollTo({top:0,behavior:'smooth'});return}oldShowPage.apply(this,arguments);setTimeout(addProfileButton,20)};window.showPage.__v51=true}
setTimeout(hook,50);setTimeout(hook,500);setTimeout(hook,1500);window.addEventListener('load',()=>setTimeout(hook,100));
window.addEventListener('storage',()=>{ensureV51();hook()});
})();
